name: It Home Auto Sign


on:
  push:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:
  
env:
  TZ: Asia/Shanghai
  
jobs:
  ithome_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v3
      - name: 'Set python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests
      - name: 'Start Sign'
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python run.py
